set_property PACKAGE_PIN D7 [get_ports a]
set_property PACKAGE_PIN F8 [get_ports b]
set_property PACKAGE_PIN G6 [get_ports result]
set_property IOSTANDARD LVCMOS18 [get_ports a]
set_property IOSTANDARD LVCMOS18 [get_ports b]
set_property IOSTANDARD LVCMOS18 [get_ports result]
